name: Test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.5.x
          - 3.6.x
          - 3.7.x
          - 3.8.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install tox
        run: |
          python -m pip install -U pip setuptools
          pip install tox tox-gh-actions

      - name: Run tests
        run: tox -p all -v
        env:
          TOX_PARALLEL_NO_SPINNER: 1